{
  path: 'yy => ee',
  customErr: Error: yy
      at /home/nikita/git/inventarisation/src/model/libs/exceptionHandling.js:51:25
      at processTicksAndRejections (node:internal/process/task_queues:93:5),
  level: 'error',
  timestamp: '2020-11-19T08:31:38.515Z',
  ms: '+0ms',
  message: 'ddd',
  stack: 'Error: ddd\n' +
    '    at Object.<anonymous> (/home/nikita/git/inventarisation/src/test.js:3:16)\n' +
    '    at Module._compile (node:internal/modules/cjs/loader:1083:30)\n' +
    '    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)\n' +
    '    at Module.load (node:internal/modules/cjs/loader:948:32)\n' +
    '    at Function.Module._load (node:internal/modules/cjs/loader:789:14)\n' +
    '    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:72:12)\n' +
    '    at node:internal/main/run_main_module:17:47'
}
{
  path: 'yy => ee',
  customErr: Error: yy
      at /home/nikita/git/inventarisation/src/model/libs/exceptionHandling.js:51:25
      at processTicksAndRejections (node:internal/process/task_queues:93:5),
  level: 'error',
  timestamp: '2020-11-19T08:32:08.718Z',
  ms: '+0ms',
  message: 'ddd',
  stack: 'Error: ddd\n' +
    '    at Object.<anonymous> (/home/nikita/git/inventarisation/src/test.js:3:16)\n' +
    '    at Module._compile (node:internal/modules/cjs/loader:1083:30)\n' +
    '    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)\n' +
    '    at Module.load (node:internal/modules/cjs/loader:948:32)\n' +
    '    at Function.Module._load (node:internal/modules/cjs/loader:789:14)\n' +
    '    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:72:12)\n' +
    '    at node:internal/main/run_main_module:17:47'
}
{
  path: 'yy => ee',
  customErr: Error: yy
      at /home/nikita/git/inventarisation/src/model/libs/exceptionHandling.js:51:25
      at processTicksAndRejections (node:internal/process/task_queues:93:5),
  level: 'error',
  timestamp: '2020-11-19T08:32:21.582Z',
  ms: '+0ms',
  message: 'ddd',
  stack: 'Error: ddd\n' +
    '    at Object.<anonymous> (/home/nikita/git/inventarisation/src/test.js:3:16)\n' +
    '    at Module._compile (node:internal/modules/cjs/loader:1083:30)\n' +
    '    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)\n' +
    '    at Module.load (node:internal/modules/cjs/loader:948:32)\n' +
    '    at Function.Module._load (node:internal/modules/cjs/loader:789:14)\n' +
    '    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:72:12)\n' +
    '    at node:internal/main/run_main_module:17:47'
}
{
  level: 'error',
  timestamp: '2020-11-19T09:19:29.120Z',
  ms: '+0ms',
  message: "Cannot read property 'app' of undefined",
  stack: "TypeError: Cannot read property 'app' of undefined\n" +
    '    at json (/home/nikita/git/inventarisation/node_modules/express/lib/response.js:256:18)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:93:5)'
}
{
  level: 'error',
  timestamp: '2020-11-19T09:19:29.162Z',
  ms: '+42ms',
  message: "Cannot read property 'app' of undefined",
  stack: "TypeError: Cannot read property 'app' of undefined\n" +
    '    at json (/home/nikita/git/inventarisation/node_modules/express/lib/response.js:256:18)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:93:5)'
}
{
  level: 'error',
  timestamp: '2020-11-19T09:19:29.172Z',
  ms: '+10ms',
  message: "Cannot read property 'app' of undefined",
  stack: "TypeError: Cannot read property 'app' of undefined\n" +
    '    at json (/home/nikita/git/inventarisation/node_modules/express/lib/response.js:256:18)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:93:5)'
}
{
  level: 'error',
  timestamp: '2020-11-19T09:19:39.416Z',
  ms: '+10s',
  message: "Cannot read property 'app' of undefined",
  stack: "TypeError: Cannot read property 'app' of undefined\n" +
    '    at json (/home/nikita/git/inventarisation/node_modules/express/lib/response.js:256:18)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:93:5)'
}
{
  level: 'error',
  timestamp: '2020-11-19T09:19:39.449Z',
  ms: '+33ms',
  message: "Cannot read property 'app' of undefined",
  stack: "TypeError: Cannot read property 'app' of undefined\n" +
    '    at json (/home/nikita/git/inventarisation/node_modules/express/lib/response.js:256:18)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:93:5)'
}
{
  level: 'error',
  timestamp: '2020-11-19T09:19:39.453Z',
  ms: '+4ms',
  message: "Cannot read property 'app' of undefined",
  stack: "TypeError: Cannot read property 'app' of undefined\n" +
    '    at json (/home/nikita/git/inventarisation/node_modules/express/lib/response.js:256:18)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:93:5)'
}
{
  level: 'error',
  timestamp: '2020-11-19T09:20:00.775Z',
  ms: '+21s',
  message: "Cannot read property 'app' of undefined",
  stack: "TypeError: Cannot read property 'app' of undefined\n" +
    '    at json (/home/nikita/git/inventarisation/node_modules/express/lib/response.js:256:18)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:93:5)'
}
{
  level: 'error',
  timestamp: '2020-11-19T09:20:00.785Z',
  ms: '+10ms',
  message: "Cannot read property 'app' of undefined",
  stack: "TypeError: Cannot read property 'app' of undefined\n" +
    '    at json (/home/nikita/git/inventarisation/node_modules/express/lib/response.js:256:18)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:93:5)'
}
{
  level: 'error',
  timestamp: '2020-11-19T09:20:00.790Z',
  ms: '+5ms',
  message: "Cannot read property 'app' of undefined",
  stack: "TypeError: Cannot read property 'app' of undefined\n" +
    '    at json (/home/nikita/git/inventarisation/node_modules/express/lib/response.js:256:18)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:93:5)'
}
{
  level: 'error',
  timestamp: '2020-11-19T09:21:31.120Z',
  ms: '+2m',
  message: "Cannot read property 'app' of undefined",
  stack: "TypeError: Cannot read property 'app' of undefined\n" +
    '    at json (/home/nikita/git/inventarisation/node_modules/express/lib/response.js:256:18)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:93:5)'
}
{
  level: 'error',
  timestamp: '2020-11-19T09:21:31.130Z',
  ms: '+10ms',
  message: "Cannot read property 'app' of undefined",
  stack: "TypeError: Cannot read property 'app' of undefined\n" +
    '    at json (/home/nikita/git/inventarisation/node_modules/express/lib/response.js:256:18)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:93:5)'
}
{
  level: 'error',
  timestamp: '2020-11-19T09:21:31.135Z',
  ms: '+5ms',
  message: "Cannot read property 'app' of undefined",
  stack: "TypeError: Cannot read property 'app' of undefined\n" +
    '    at json (/home/nikita/git/inventarisation/node_modules/express/lib/response.js:256:18)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:93:5)'
}
{
  level: 'error',
  timestamp: '2020-11-19T09:22:03.664Z',
  ms: '+0ms',
  message: "Cannot read property 'app' of undefined",
  stack: "TypeError: Cannot read property 'app' of undefined\n" +
    '    at json (/home/nikita/git/inventarisation/node_modules/express/lib/response.js:256:18)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:93:5)'
}
{
  level: 'error',
  timestamp: '2020-11-19T09:22:03.711Z',
  ms: '+47ms',
  message: "Cannot read property 'app' of undefined",
  stack: "TypeError: Cannot read property 'app' of undefined\n" +
    '    at json (/home/nikita/git/inventarisation/node_modules/express/lib/response.js:256:18)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:93:5)'
}
{
  level: 'error',
  timestamp: '2020-11-19T09:22:03.716Z',
  ms: '+5ms',
  message: "Cannot read property 'app' of undefined",
  stack: "TypeError: Cannot read property 'app' of undefined\n" +
    '    at json (/home/nikita/git/inventarisation/node_modules/express/lib/response.js:256:18)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:93:5)'
}
{
  level: 'error',
  timestamp: '2020-11-19T09:22:40.441Z',
  ms: '+37s',
  message: "Cannot read property 'app' of undefined",
  stack: "TypeError: Cannot read property 'app' of undefined\n" +
    '    at json (/home/nikita/git/inventarisation/node_modules/express/lib/response.js:256:18)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:93:5)'
}
{
  path: 'checkAuthorizationByRoleMlw',
  customErr: Error: checkAuthorizationByRoleMlw
      at /home/nikita/git/inventarisation/src/model/libs/exceptionHandling.js:51:25
      at /home/nikita/git/inventarisation/src/model/libs/exceptionHandling.js:78:29
      at processTicksAndRejections (node:internal/process/task_queues:93:5),
  level: 'error',
  timestamp: '2020-11-26T08:53:05.141Z',
  ms: '+0ms',
  message: 'undefined was passed to findById',
  stack: 'Error: undefined was passed to findById\n' +
    '    at assertIdNotUndefined (/home/nikita/git/inventarisation/node_modules/objection/lib/utils/assert.js:18:11)\n' +
    '    at FindByIdOperation.onBuild (/home/nikita/git/inventarisation/node_modules/objection/lib/queryBuilder/operations/FindByIdOperation.js:19:7)\n' +
    '    at QueryBuilder.callOperationMethod (/home/nikita/git/inventarisation/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:350:33)\n' +
    '    at /home/nikita/git/inventarisation/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:437:14\n' +
    '    at QueryBuilder.forEachOperation (/home/nikita/git/inventarisation/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:287:37)\n' +
    '    at QueryBuilder.executeOnBuild (/home/nikita/git/inventarisation/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:435:10)\n' +
    '    at callOnBuildHooks (/home/nikita/git/inventarisation/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1579:11)\n' +
    '    at doExecute (/home/nikita/git/inventarisation/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1469:13)\n' +
    '    at QueryBuilder.execute (/home/nikita/git/inventarisation/node_modules/objection/lib/queryBuilder/QueryBuilder.js:684:28)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:93:5)'
}
{
  path: 'checkAuthorizationByRoleMlw',
  customErr: Error: checkAuthorizationByRoleMlw
      at /home/nikita/git/inventarisation/src/model/libs/exceptionHandling.js:51:25
      at /home/nikita/git/inventarisation/src/model/libs/exceptionHandling.js:78:29
      at processTicksAndRejections (node:internal/process/task_queues:93:5),
  level: 'error',
  timestamp: '2020-11-26T08:55:00.194Z',
  ms: '+0ms',
  message: 'undefined was passed to findById',
  stack: 'Error: undefined was passed to findById\n' +
    '    at assertIdNotUndefined (/home/nikita/git/inventarisation/node_modules/objection/lib/utils/assert.js:18:11)\n' +
    '    at FindByIdOperation.onBuild (/home/nikita/git/inventarisation/node_modules/objection/lib/queryBuilder/operations/FindByIdOperation.js:19:7)\n' +
    '    at QueryBuilder.callOperationMethod (/home/nikita/git/inventarisation/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:350:33)\n' +
    '    at /home/nikita/git/inventarisation/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:437:14\n' +
    '    at QueryBuilder.forEachOperation (/home/nikita/git/inventarisation/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:287:37)\n' +
    '    at QueryBuilder.executeOnBuild (/home/nikita/git/inventarisation/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:435:10)\n' +
    '    at callOnBuildHooks (/home/nikita/git/inventarisation/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1579:11)\n' +
    '    at doExecute (/home/nikita/git/inventarisation/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1469:13)\n' +
    '    at QueryBuilder.execute (/home/nikita/git/inventarisation/node_modules/objection/lib/queryBuilder/QueryBuilder.js:684:28)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:93:5)'
}
{
  path: 'checkAuthorizationByRoleMlw',
  customErr: Error: checkAuthorizationByRoleMlw
      at /home/nikita/git/inventarisation/src/model/libs/exceptionHandling.js:51:25
      at /home/nikita/git/inventarisation/src/model/libs/exceptionHandling.js:78:29
      at processTicksAndRejections (node:internal/process/task_queues:93:5),
  level: 'error',
  timestamp: '2020-11-26T08:55:47.386Z',
  ms: '+0ms',
  message: 'Ajv is not a constructor',
  stack: 'TypeError: Ajv is not a constructor\n' +
    '    at /home/nikita/git/inventarisation/src/model/libs/authorization.js:30:17\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:93:5)'
}
{
  path: 'checkAuthorizationByRoleMlw',
  customErr: Error: checkAuthorizationByRoleMlw
      at /home/nikita/git/inventarisation/src/model/libs/exceptionHandling.js:51:25
      at /home/nikita/git/inventarisation/src/model/libs/exceptionHandling.js:78:29
      at processTicksAndRejections (node:internal/process/task_queues:93:5),
  level: 'error',
  timestamp: '2020-11-26T08:56:20.932Z',
  ms: '+0ms',
  message: 'id.replace is not a function',
  stack: 'TypeError: id.replace is not a function\n' +
    '    at Function.normalizeId (/home/nikita/git/inventarisation/node_modules/ajv/lib/compile/resolve.js:221:18)\n' +
    '    at Ajv._addSchema (/home/nikita/git/inventarisation/node_modules/ajv/lib/ajv.js:301:20)\n' +
    '    at Ajv.compile (/home/nikita/git/inventarisation/node_modules/ajv/lib/ajv.js:113:24)\n' +
    '    at /home/nikita/git/inventarisation/src/model/libs/authorization.js:31:26\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:93:5)'
}
{
  path: 'checkAuthorizationByRoleMlw',
  customErr: Error: checkAuthorizationByRoleMlw
      at /home/nikita/git/inventarisation/src/model/libs/exceptionHandling.js:51:25
      at /home/nikita/git/inventarisation/src/model/libs/exceptionHandling.js:78:29
      at processTicksAndRejections (node:internal/process/task_queues:93:5),
  level: 'error',
  timestamp: '2020-11-26T08:57:42.829Z',
  ms: '+0ms',
  message: 'id.replace is not a function',
  stack: 'TypeError: id.replace is not a function\n' +
    '    at Function.normalizeId (/home/nikita/git/inventarisation/node_modules/ajv/lib/compile/resolve.js:221:18)\n' +
    '    at Ajv._addSchema (/home/nikita/git/inventarisation/node_modules/ajv/lib/ajv.js:301:20)\n' +
    '    at Ajv.compile (/home/nikita/git/inventarisation/node_modules/ajv/lib/ajv.js:113:24)\n' +
    '    at /home/nikita/git/inventarisation/src/model/libs/authorization.js:31:26\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:93:5)'
}
{
  path: 'checkAuthorizationByRoleMlw',
  customErr: Error: checkAuthorizationByRoleMlw
      at /home/nikita/git/inventarisation/src/model/libs/exceptionHandling.js:51:25
      at /home/nikita/git/inventarisation/src/model/libs/exceptionHandling.js:78:29
      at processTicksAndRejections (node:internal/process/task_queues:93:5),
  level: 'error',
  timestamp: '2020-11-26T08:58:23.593Z',
  ms: '+0ms',
  message: 'id.replace is not a function',
  stack: 'TypeError: id.replace is not a function\n' +
    '    at Function.normalizeId (/home/nikita/git/inventarisation/node_modules/ajv/lib/compile/resolve.js:221:18)\n' +
    '    at Ajv._addSchema (/home/nikita/git/inventarisation/node_modules/ajv/lib/ajv.js:301:20)\n' +
    '    at Ajv.compile (/home/nikita/git/inventarisation/node_modules/ajv/lib/ajv.js:113:24)\n' +
    '    at /home/nikita/git/inventarisation/src/model/libs/authorization.js:31:26\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:93:5)'
}
{
  path: 'checkAuthorizationByRoleMlw',
  customErr: Error: checkAuthorizationByRoleMlw
      at /home/nikita/git/inventarisation/src/model/libs/exceptionHandling.js:51:25
      at /home/nikita/git/inventarisation/src/model/libs/exceptionHandling.js:78:29
      at processTicksAndRejections (node:internal/process/task_queues:93:5),
  level: 'error',
  timestamp: '2020-11-26T09:03:11.645Z',
  ms: '+0ms',
  message: 'id.replace is not a function',
  stack: 'TypeError: id.replace is not a function\n' +
    '    at Function.normalizeId (/home/nikita/git/inventarisation/node_modules/ajv/lib/compile/resolve.js:221:18)\n' +
    '    at Ajv._addSchema (/home/nikita/git/inventarisation/node_modules/ajv/lib/ajv.js:301:20)\n' +
    '    at Ajv.compile (/home/nikita/git/inventarisation/node_modules/ajv/lib/ajv.js:113:24)\n' +
    '    at /home/nikita/git/inventarisation/src/model/libs/authorization.js:32:26\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:93:5)'
}
{
  name: 'DBError',
  nativeError: Error: insert into `device` (`brand_id`, `category_id`, `comments`, `date_ purchase`, `date_warranty_end`, `inv_number`, `location_id`, `model`, `price`, `specifications`, `status_id`, `supplier_id`, `user_id`) values (1, 3, 'ghghgh', '2018-11-13', '2018-11-13', 'ssds-222', 1, 'sdsdsd', 1233, {"latency":1}, 1, 1, 2) - Unknown column 'date_ purchase' in 'field list'
      at Packet.asError (C:\Users\Admin\Documents\inventarisation\node_modules\mysql2\lib\packets\packet.js:712:17)
      at Query.execute (C:\Users\Admin\Documents\inventarisation\node_modules\mysql2\lib\commands\command.js:28:26)
      at Connection.handlePacket (C:\Users\Admin\Documents\inventarisation\node_modules\mysql2\lib\connection.js:425:32)
      at PacketParser.onPacket (C:\Users\Admin\Documents\inventarisation\node_modules\mysql2\lib\connection.js:75:12)
      at PacketParser.executeStart (C:\Users\Admin\Documents\inventarisation\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\Admin\Documents\inventarisation\node_modules\mysql2\lib\connection.js:82:25)
      at Socket.emit (events.js:315:20)
      at addChunk (_stream_readable.js:295:12)
      at readableAddChunk (_stream_readable.js:271:9)
      at Socket.Readable.push (_stream_readable.js:212:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
    code: 'ER_BAD_FIELD_ERROR',
    errno: 1054,
    sqlState: '42S22',
    sqlMessage: "Unknown column 'date_ purchase' in 'field list'"
  },
  client: 'mysql',
  path: 'insertTable: device',
  customErr: Error: insertTable: device
      at C:\Users\Admin\Documents\inventarisation\src\model\libs\exceptionHandling.js:51:25
      at processTicksAndRejections (internal/process/task_queues.js:97:5),
  level: 'error',
  timestamp: '2020-12-02T05:56:21.859Z',
  ms: '+0ms',
  message: 'insert into `device` (`brand_id`, `category_id`, `comments`, `date_ purchase`, `date_warranty_end`, `inv_number`, `location_id`, `model`, `price`, `specifications`, `status_id`, `supplier_id`, `user_id`) values (1, 3, \'ghghgh\', \'2018-11-13\', \'2018-11-13\', \'ssds-222\', 1, \'sdsdsd\', 1233, {"latency":1}, 1, 1, 2) - Unknown column \'date_ purchase\' in \'field list\'',
  stack: 'DBError: insert into `device` (`brand_id`, `category_id`, `comments`, `date_ purchase`, `date_warranty_end`, `inv_number`, `location_id`, `model`, `price`, `specifications`, `status_id`, `supplier_id`, `user_id`) values (1, 3, \'ghghgh\', \'2018-11-13\', \'2018-11-13\', \'ssds-222\', 1, \'sdsdsd\', 1233, {"latency":1}, 1, 1, 2) - Unknown column \'date_ purchase\' in \'field list\'\n' +
    '    at wrapError (C:\\Users\\Admin\\Documents\\inventarisation\\node_modules\\db-errors\\lib\\dbErrors.js:19:14)\n' +
    '    at handleExecuteError (C:\\Users\\Admin\\Documents\\inventarisation\\node_modules\\objection\\lib\\queryBuilder\\QueryBuilder.js:1506:32)\n' +
    '    at QueryBuilder.execute (C:\\Users\\Admin\\Documents\\inventarisation\\node_modules\\objection\\lib\\queryBuilder\\QueryBuilder.js:687:20)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:97:5)'
}
{
  name: 'DBError',
  nativeError: Error: insert into `device` (`brand_id`, `category_id`, `comments`, `date_ purchase`, `date_purchase`, `date_warranty_end`, `inv_number`, `location_id`, `model`, `price`, `specifications`, `status_id`, `supplier_id`, `user_id`) values (1, 3, 'ghghgh', '2018-11-13', NULL, '2018-11-13T00:00:00.000Z', 'ssds-222', 1, 'sdsdsd', 1233, {"latency":1}, 1, 1, 2) - Unknown column 'date_ purchase' in 'field list'
      at Packet.asError (C:\Users\Admin\Documents\inventarisation\node_modules\mysql2\lib\packets\packet.js:712:17)
      at Query.execute (C:\Users\Admin\Documents\inventarisation\node_modules\mysql2\lib\commands\command.js:28:26)
      at Connection.handlePacket (C:\Users\Admin\Documents\inventarisation\node_modules\mysql2\lib\connection.js:425:32)
      at PacketParser.onPacket (C:\Users\Admin\Documents\inventarisation\node_modules\mysql2\lib\connection.js:75:12)
      at PacketParser.executeStart (C:\Users\Admin\Documents\inventarisation\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\Admin\Documents\inventarisation\node_modules\mysql2\lib\connection.js:82:25)
      at Socket.emit (events.js:315:20)
      at addChunk (_stream_readable.js:295:12)
      at readableAddChunk (_stream_readable.js:271:9)
      at Socket.Readable.push (_stream_readable.js:212:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
    code: 'ER_BAD_FIELD_ERROR',
    errno: 1054,
    sqlState: '42S22',
    sqlMessage: "Unknown column 'date_ purchase' in 'field list'"
  },
  client: 'mysql',
  path: 'insertTable: device',
  customErr: Error: insertTable: device
      at C:\Users\Admin\Documents\inventarisation\src\model\libs\exceptionHandling.js:51:25
      at processTicksAndRejections (internal/process/task_queues.js:97:5),
  level: 'error',
  timestamp: '2020-12-02T07:41:51.006Z',
  ms: '+0ms',
  message: 'insert into `device` (`brand_id`, `category_id`, `comments`, `date_ purchase`, `date_purchase`, `date_warranty_end`, `inv_number`, `location_id`, `model`, `price`, `specifications`, `status_id`, `supplier_id`, `user_id`) values (1, 3, \'ghghgh\', \'2018-11-13\', NULL, \'2018-11-13T00:00:00.000Z\', \'ssds-222\', 1, \'sdsdsd\', 1233, {"latency":1}, 1, 1, 2) - Unknown column \'date_ purchase\' in \'field list\'',
  stack: 'DBError: insert into `device` (`brand_id`, `category_id`, `comments`, `date_ purchase`, `date_purchase`, `date_warranty_end`, `inv_number`, `location_id`, `model`, `price`, `specifications`, `status_id`, `supplier_id`, `user_id`) values (1, 3, \'ghghgh\', \'2018-11-13\', NULL, \'2018-11-13T00:00:00.000Z\', \'ssds-222\', 1, \'sdsdsd\', 1233, {"latency":1}, 1, 1, 2) - Unknown column \'date_ purchase\' in \'field list\'\n' +
    '    at wrapError (C:\\Users\\Admin\\Documents\\inventarisation\\node_modules\\db-errors\\lib\\dbErrors.js:19:14)\n' +
    '    at handleExecuteError (C:\\Users\\Admin\\Documents\\inventarisation\\node_modules\\objection\\lib\\queryBuilder\\QueryBuilder.js:1506:32)\n' +
    '    at QueryBuilder.execute (C:\\Users\\Admin\\Documents\\inventarisation\\node_modules\\objection\\lib\\queryBuilder\\QueryBuilder.js:687:20)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:97:5)'
}
{
  name: 'DBError',
  nativeError: Error: insert into `device` (`brand_id`, `category_id`, `comments`, `date_ purchase`, `date_purchase`, `date_warranty_end`, `inv_number`, `location_id`, `model`, `price`, `specifications`, `status_id`, `supplier_id`, `user_id`) values (1, 3, 'ghghgh', '2018-11-13', NULL, '2018-11-13T00:00:00.000Z', 'ssds-222', 1, 'sdsdsd', 1233, {"latency":1}, 1, 1, 2) - Unknown column 'date_ purchase' in 'field list'
      at Packet.asError (C:\Users\Admin\Documents\inventarisation\node_modules\mysql2\lib\packets\packet.js:712:17)
      at Query.execute (C:\Users\Admin\Documents\inventarisation\node_modules\mysql2\lib\commands\command.js:28:26)
      at Connection.handlePacket (C:\Users\Admin\Documents\inventarisation\node_modules\mysql2\lib\connection.js:425:32)
      at PacketParser.onPacket (C:\Users\Admin\Documents\inventarisation\node_modules\mysql2\lib\connection.js:75:12)
      at PacketParser.executeStart (C:\Users\Admin\Documents\inventarisation\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\Admin\Documents\inventarisation\node_modules\mysql2\lib\connection.js:82:25)
      at Socket.emit (events.js:315:20)
      at addChunk (_stream_readable.js:295:12)
      at readableAddChunk (_stream_readable.js:271:9)
      at Socket.Readable.push (_stream_readable.js:212:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
    code: 'ER_BAD_FIELD_ERROR',
    errno: 1054,
    sqlState: '42S22',
    sqlMessage: "Unknown column 'date_ purchase' in 'field list'"
  },
  client: 'mysql',
  path: 'insertTable: device',
  customErr: Error: insertTable: device
      at C:\Users\Admin\Documents\inventarisation\src\model\libs\exceptionHandling.js:51:25
      at processTicksAndRejections (internal/process/task_queues.js:97:5),
  level: 'error',
  timestamp: '2020-12-02T07:42:25.580Z',
  ms: '+0ms',
  message: 'insert into `device` (`brand_id`, `category_id`, `comments`, `date_ purchase`, `date_purchase`, `date_warranty_end`, `inv_number`, `location_id`, `model`, `price`, `specifications`, `status_id`, `supplier_id`, `user_id`) values (1, 3, \'ghghgh\', \'2018-11-13\', NULL, \'2018-11-13T00:00:00.000Z\', \'ssds-222\', 1, \'sdsdsd\', 1233, {"latency":1}, 1, 1, 2) - Unknown column \'date_ purchase\' in \'field list\'',
  stack: 'DBError: insert into `device` (`brand_id`, `category_id`, `comments`, `date_ purchase`, `date_purchase`, `date_warranty_end`, `inv_number`, `location_id`, `model`, `price`, `specifications`, `status_id`, `supplier_id`, `user_id`) values (1, 3, \'ghghgh\', \'2018-11-13\', NULL, \'2018-11-13T00:00:00.000Z\', \'ssds-222\', 1, \'sdsdsd\', 1233, {"latency":1}, 1, 1, 2) - Unknown column \'date_ purchase\' in \'field list\'\n' +
    '    at wrapError (C:\\Users\\Admin\\Documents\\inventarisation\\node_modules\\db-errors\\lib\\dbErrors.js:19:14)\n' +
    '    at handleExecuteError (C:\\Users\\Admin\\Documents\\inventarisation\\node_modules\\objection\\lib\\queryBuilder\\QueryBuilder.js:1506:32)\n' +
    '    at QueryBuilder.execute (C:\\Users\\Admin\\Documents\\inventarisation\\node_modules\\objection\\lib\\queryBuilder\\QueryBuilder.js:687:20)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:97:5)'
}
{
  name: 'DBError',
  nativeError: Error: insert into `device` (`brand_id`, `category_id`, `comments`, `date_purchase`, `date_warranty_end`, `inv_number`, `location_id`, `model`, `price`, `specifications`, `status_id`, `supplier_id`, `user_id`) values (1, 3, 'ghghgh', '2018-11-13T00:00:00.000Z', '2018-11-13T00:00:00.000Z', 'ssds-222', 1, 'sdsdsd', 1233, {"latency":1}, 1, 1, 2) - Unknown column 'latency' in 'field list'
      at Packet.asError (C:\Users\Admin\Documents\inventarisation\node_modules\mysql2\lib\packets\packet.js:712:17)
      at Query.execute (C:\Users\Admin\Documents\inventarisation\node_modules\mysql2\lib\commands\command.js:28:26)
      at Connection.handlePacket (C:\Users\Admin\Documents\inventarisation\node_modules\mysql2\lib\connection.js:425:32)
      at PacketParser.onPacket (C:\Users\Admin\Documents\inventarisation\node_modules\mysql2\lib\connection.js:75:12)
      at PacketParser.executeStart (C:\Users\Admin\Documents\inventarisation\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\Admin\Documents\inventarisation\node_modules\mysql2\lib\connection.js:82:25)
      at Socket.emit (events.js:315:20)
      at addChunk (_stream_readable.js:295:12)
      at readableAddChunk (_stream_readable.js:271:9)
      at Socket.Readable.push (_stream_readable.js:212:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
    code: 'ER_BAD_FIELD_ERROR',
    errno: 1054,
    sqlState: '42S22',
    sqlMessage: "Unknown column 'latency' in 'field list'"
  },
  client: 'mysql',
  path: 'insertTable: device',
  customErr: Error: insertTable: device
      at C:\Users\Admin\Documents\inventarisation\src\model\libs\exceptionHandling.js:51:25
      at processTicksAndRejections (internal/process/task_queues.js:97:5),
  level: 'error',
  timestamp: '2020-12-02T07:43:48.113Z',
  ms: '+0ms',
  message: 'insert into `device` (`brand_id`, `category_id`, `comments`, `date_purchase`, `date_warranty_end`, `inv_number`, `location_id`, `model`, `price`, `specifications`, `status_id`, `supplier_id`, `user_id`) values (1, 3, \'ghghgh\', \'2018-11-13T00:00:00.000Z\', \'2018-11-13T00:00:00.000Z\', \'ssds-222\', 1, \'sdsdsd\', 1233, {"latency":1}, 1, 1, 2) - Unknown column \'latency\' in \'field list\'',
  stack: 'DBError: insert into `device` (`brand_id`, `category_id`, `comments`, `date_purchase`, `date_warranty_end`, `inv_number`, `location_id`, `model`, `price`, `specifications`, `status_id`, `supplier_id`, `user_id`) values (1, 3, \'ghghgh\', \'2018-11-13T00:00:00.000Z\', \'2018-11-13T00:00:00.000Z\', \'ssds-222\', 1, \'sdsdsd\', 1233, {"latency":1}, 1, 1, 2) - Unknown column \'latency\' in \'field list\'\n' +
    '    at wrapError (C:\\Users\\Admin\\Documents\\inventarisation\\node_modules\\db-errors\\lib\\dbErrors.js:19:14)\n' +
    '    at handleExecuteError (C:\\Users\\Admin\\Documents\\inventarisation\\node_modules\\objection\\lib\\queryBuilder\\QueryBuilder.js:1506:32)\n' +
    '    at QueryBuilder.execute (C:\\Users\\Admin\\Documents\\inventarisation\\node_modules\\objection\\lib\\queryBuilder\\QueryBuilder.js:687:20)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:97:5)'
}
{
  name: 'DBError',
  nativeError: Error: insert into `device` (`brand_id`, `category_id`, `comments`, `date_purchase`, `date_warranty_end`, `inv_number`, `location_id`, `model`, `price`, `specifications`, `status_id`, `supplier_id`, `user_id`) values (1, 3, 'ghghgh', '2018-11-13T00:00:00.000Z', '2018-11-13T00:00:00.000Z', 'ssds-222', 1, 'sdsdsd', 1233, {"latency":1}, 1, 1, 2) - Unknown column 'latency' in 'field list'
      at Packet.asError (C:\Users\Admin\Documents\inventarisation\node_modules\mysql2\lib\packets\packet.js:712:17)
      at Query.execute (C:\Users\Admin\Documents\inventarisation\node_modules\mysql2\lib\commands\command.js:28:26)
      at Connection.handlePacket (C:\Users\Admin\Documents\inventarisation\node_modules\mysql2\lib\connection.js:425:32)
      at PacketParser.onPacket (C:\Users\Admin\Documents\inventarisation\node_modules\mysql2\lib\connection.js:75:12)
      at PacketParser.executeStart (C:\Users\Admin\Documents\inventarisation\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\Admin\Documents\inventarisation\node_modules\mysql2\lib\connection.js:82:25)
      at Socket.emit (events.js:315:20)
      at addChunk (_stream_readable.js:295:12)
      at readableAddChunk (_stream_readable.js:271:9)
      at Socket.Readable.push (_stream_readable.js:212:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
    code: 'ER_BAD_FIELD_ERROR',
    errno: 1054,
    sqlState: '42S22',
    sqlMessage: "Unknown column 'latency' in 'field list'"
  },
  client: 'mysql',
  path: 'insertTable: device',
  customErr: Error: insertTable: device
      at C:\Users\Admin\Documents\inventarisation\src\model\libs\exceptionHandling.js:51:25
      at processTicksAndRejections (internal/process/task_queues.js:97:5),
  level: 'error',
  timestamp: '2020-12-02T07:50:09.923Z',
  ms: '+0ms',
  message: 'insert into `device` (`brand_id`, `category_id`, `comments`, `date_purchase`, `date_warranty_end`, `inv_number`, `location_id`, `model`, `price`, `specifications`, `status_id`, `supplier_id`, `user_id`) values (1, 3, \'ghghgh\', \'2018-11-13T00:00:00.000Z\', \'2018-11-13T00:00:00.000Z\', \'ssds-222\', 1, \'sdsdsd\', 1233, {"latency":1}, 1, 1, 2) - Unknown column \'latency\' in \'field list\'',
  stack: 'DBError: insert into `device` (`brand_id`, `category_id`, `comments`, `date_purchase`, `date_warranty_end`, `inv_number`, `location_id`, `model`, `price`, `specifications`, `status_id`, `supplier_id`, `user_id`) values (1, 3, \'ghghgh\', \'2018-11-13T00:00:00.000Z\', \'2018-11-13T00:00:00.000Z\', \'ssds-222\', 1, \'sdsdsd\', 1233, {"latency":1}, 1, 1, 2) - Unknown column \'latency\' in \'field list\'\n' +
    '    at wrapError (C:\\Users\\Admin\\Documents\\inventarisation\\node_modules\\db-errors\\lib\\dbErrors.js:19:14)\n' +
    '    at handleExecuteError (C:\\Users\\Admin\\Documents\\inventarisation\\node_modules\\objection\\lib\\queryBuilder\\QueryBuilder.js:1506:32)\n' +
    '    at QueryBuilder.execute (C:\\Users\\Admin\\Documents\\inventarisation\\node_modules\\objection\\lib\\queryBuilder\\QueryBuilder.js:687:20)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:97:5)'
}
{
  name: 'DBError',
  nativeError: Error: insert into `device` (`brand_id`, `category_id`, `comments`, `date_purchase`, `date_warranty_end`, `inv_number`, `location_id`, `model`, `price`, `specifications`, `status_id`, `supplier_id`, `user_id`) values (1, 3, 'ghghgh', '2018-11-13T00:00:00.000Z', '2018-11-13T00:00:00.000Z', 'ssds-222', 1, 'sdsdsd', 1233, {"latency":1}, 1, 1, 2) - Unknown column 'latency' in 'field list'
      at Packet.asError (C:\Users\Admin\Documents\inventarisation\node_modules\mysql2\lib\packets\packet.js:712:17)
      at Query.execute (C:\Users\Admin\Documents\inventarisation\node_modules\mysql2\lib\commands\command.js:28:26)
      at Connection.handlePacket (C:\Users\Admin\Documents\inventarisation\node_modules\mysql2\lib\connection.js:425:32)
      at PacketParser.onPacket (C:\Users\Admin\Documents\inventarisation\node_modules\mysql2\lib\connection.js:75:12)
      at PacketParser.executeStart (C:\Users\Admin\Documents\inventarisation\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\Admin\Documents\inventarisation\node_modules\mysql2\lib\connection.js:82:25)
      at Socket.emit (events.js:315:20)
      at addChunk (_stream_readable.js:295:12)
      at readableAddChunk (_stream_readable.js:271:9)
      at Socket.Readable.push (_stream_readable.js:212:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
    code: 'ER_BAD_FIELD_ERROR',
    errno: 1054,
    sqlState: '42S22',
    sqlMessage: "Unknown column 'latency' in 'field list'"
  },
  client: 'mysql',
  path: 'insertTable: device',
  customErr: Error: insertTable: device
      at C:\Users\Admin\Documents\inventarisation\src\model\libs\exceptionHandling.js:51:25
      at processTicksAndRejections (internal/process/task_queues.js:97:5),
  level: 'error',
  timestamp: '2020-12-02T07:50:29.970Z',
  ms: '+0ms',
  message: 'insert into `device` (`brand_id`, `category_id`, `comments`, `date_purchase`, `date_warranty_end`, `inv_number`, `location_id`, `model`, `price`, `specifications`, `status_id`, `supplier_id`, `user_id`) values (1, 3, \'ghghgh\', \'2018-11-13T00:00:00.000Z\', \'2018-11-13T00:00:00.000Z\', \'ssds-222\', 1, \'sdsdsd\', 1233, {"latency":1}, 1, 1, 2) - Unknown column \'latency\' in \'field list\'',
  stack: 'DBError: insert into `device` (`brand_id`, `category_id`, `comments`, `date_purchase`, `date_warranty_end`, `inv_number`, `location_id`, `model`, `price`, `specifications`, `status_id`, `supplier_id`, `user_id`) values (1, 3, \'ghghgh\', \'2018-11-13T00:00:00.000Z\', \'2018-11-13T00:00:00.000Z\', \'ssds-222\', 1, \'sdsdsd\', 1233, {"latency":1}, 1, 1, 2) - Unknown column \'latency\' in \'field list\'\n' +
    '    at wrapError (C:\\Users\\Admin\\Documents\\inventarisation\\node_modules\\db-errors\\lib\\dbErrors.js:19:14)\n' +
    '    at handleExecuteError (C:\\Users\\Admin\\Documents\\inventarisation\\node_modules\\objection\\lib\\queryBuilder\\QueryBuilder.js:1506:32)\n' +
    '    at QueryBuilder.execute (C:\\Users\\Admin\\Documents\\inventarisation\\node_modules\\objection\\lib\\queryBuilder\\QueryBuilder.js:687:20)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:97:5)'
}
{
  level: 'error',
  timestamp: '2020-12-04T11:46:50.275Z',
  ms: '+0ms',
  message: 'patchAndFetch can only be called for instance operations',
  stack: 'Error: patchAndFetch can only be called for instance operations\n' +
    '    at C:\\Users\\Admin\\Documents\\inventarisation\\node_modules\\objection\\lib\\queryBuilder\\QueryBuilder.js:1025:15\n' +
    '    at writeOperation (C:\\Users\\Admin\\Documents\\inventarisation\\node_modules\\objection\\lib\\queryBuilder\\QueryBuilder.js:1683:5)\n' +
    '    at QueryBuilder.patchAndFetch (C:\\Users\\Admin\\Documents\\inventarisation\\node_modules\\objection\\lib\\queryBuilder\\QueryBuilder.js:1021:12)\n' +
    '    at C:\\Users\\Admin\\Documents\\inventarisation\\src\\routes\\command.js:17:61\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:97:5)'
}
{
  path: 'expressMwFn',
  customErr: Error: expressMwFn
      at C:\Users\Admin\Documents\inventarisation\src\model\libs\exceptionHandling.js:51:25
      at C:\Users\Admin\Documents\inventarisation\src\model\libs\exceptionHandling.js:78:29
      at processTicksAndRejections (internal/process/task_queues.js:97:5),
  level: 'error',
  timestamp: '2020-12-06T22:18:07.414Z',
  ms: '+0ms',
  message: "Cannot read property 'req' of undefined",
  stack: "TypeError: Cannot read property 'req' of undefined\n" +
    '    at C:\\Users\\Admin\\Documents\\inventarisation\\src\\model\\libs\\express-openapi-validator.js:85:36\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:97:5)'
}
{
  path: 'expressMwFn',
  customErr: Error: expressMwFn
      at C:\Users\Admin\Documents\inventarisation\src\model\libs\exceptionHandling.js:51:25
      at C:\Users\Admin\Documents\inventarisation\src\model\libs\exceptionHandling.js:78:29
      at processTicksAndRejections (internal/process/task_queues.js:97:5),
  level: 'error',
  timestamp: '2020-12-06T22:30:14.532Z',
  ms: '+0ms',
  message: "Cannot read property 'req' of undefined",
  stack: "TypeError: Cannot read property 'req' of undefined\n" +
    '    at C:\\Users\\Admin\\Documents\\inventarisation\\src\\model\\libs\\express-openapi-validator.js:86:36\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:97:5)'
}
{
  path: 'expressMwFn',
  customErr: Error: expressMwFn
      at C:\Users\Admin\Documents\inventarisation\src\model\libs\exceptionHandling.js:51:25
      at C:\Users\Admin\Documents\inventarisation\src\model\libs\exceptionHandling.js:78:29
      at processTicksAndRejections (internal/process/task_queues.js:97:5),
  level: 'error',
  timestamp: '2020-12-06T22:30:35.868Z',
  ms: '+0ms',
  message: "Cannot read property 'req' of undefined",
  stack: "TypeError: Cannot read property 'req' of undefined\n" +
    '    at C:\\Users\\Admin\\Documents\\inventarisation\\src\\model\\libs\\express-openapi-validator.js:86:36\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:97:5)'
}
{
  path: 'expressMwFn',
  customErr: Error: expressMwFn
      at C:\Users\Admin\Documents\inventarisation\src\model\libs\exceptionHandling.js:51:25
      at C:\Users\Admin\Documents\inventarisation\src\model\libs\exceptionHandling.js:78:29
      at processTicksAndRejections (internal/process/task_queues.js:97:5),
  level: 'error',
  timestamp: '2020-12-06T22:54:43.083Z',
  ms: '+0ms',
  message: "Cannot read property 'query' of undefined",
  stack: "TypeError: Cannot read property 'query' of undefined\n" +
    '    at C:\\Users\\Admin\\Documents\\inventarisation\\src\\model\\libs\\express-openapi-validator.js:85:40\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:97:5)'
}
{
  path: 'expressMwFn',
  customErr: Error: expressMwFn
      at C:\Users\Admin\Documents\inventarisation\src\model\libs\exceptionHandling.js:51:25
      at C:\Users\Admin\Documents\inventarisation\src\model\libs\exceptionHandling.js:78:29
      at processTicksAndRejections (internal/process/task_queues.js:97:5),
  level: 'error',
  timestamp: '2020-12-06T22:55:41.948Z',
  ms: '+0ms',
  message: "Cannot read property 'query' of undefined",
  stack: "TypeError: Cannot read property 'query' of undefined\n" +
    '    at C:\\Users\\Admin\\Documents\\inventarisation\\src\\model\\libs\\express-openapi-validator.js:85:40\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:97:5)'
}
